Add support for view inputs
JuliaSmoothOptimizers/CUTEst.jl pull request #269
Opened 2021-08-28 23:32 UTC by sshin23

Hey JSO devs, we've been using CUTEst.jl for benchmarking our solver [MadNLP.jl](https://github.com/sshin23/MadNLP.jl), and we recently found that JSO's current julia interface does not efficiently handle view inputs. Please consider merging this PR.

This PR adds better support for view inputs for CUTEst.jl's julia interface.

The current CUTEst.jl julia interface converts any `AbstractVector` input to `Vector{Float64}` to make it compatible with subsequent ccalls, and this process accompanies memory allocations. But when the AbstractVector is a stride-one array (which typically comes from a view of a `Vector` over a `UnitRange`), this can be avoided by directly passing it to C functions. 

I have added the definition for `StrideOneVector{T}`, and replaced the type specifications in the functions from `::Vector{Float64}` to `::StrideOneVector{Float64}`. This change allows directly using stride-one vectors as inputs to the C functions instead of allocating more memory. I have also added a test for `StrideOneVector{T}` in `test_core.jl`.

2021-08-30 22:59 UTC, dpo requested changes
Many thanks for this. Just a few rather unsubstantial comments for now.

2021-08-30 22:59 UTC, dpo commented on src/CUTEst.jl
> +StrideOneVector{T}=Union{
```suggestion
StrideOneVector{T} = Union{
```

2021-08-30 22:59 UTC, dpo commented on src/CUTEst.jl
> +    Vector{T},
```suggestion
  Vector{T},
```

2021-08-30 22:59 UTC, dpo commented on src/CUTEst.jl
> +    SubArray{T,1,Array{T,1},Tuple{UnitRange{U}},true} where {U<:Integer}
```suggestion
  SubArray{T, 1, Vector{T}, Tuple{UnitRange{U}}, true} where {U <: Integer}
```

2021-09-01 19:58 UTC, abelsiqueira approved these changes
Thanks for the PR, very good stuff!

2021-09-01 21:49 UTC, merged

2021-09-01 21:49 UTC, dpo commented
thank you!

2021-09-02 02:10 UTC, sshin23 commented
thanks for the merge!