Add linear API
JuliaSmoothOptimizers/CUTEst.jl pull request #284
Opened 2022-07-11 22:54 UTC by tmigot

2022-07-15 02:34 UTC, dpo requested changes

2022-07-15 02:34 UTC, dpo commented on src/julia_interface.jl
> +  st = view(Cint[0; 0], 1:1)
why isn't `Cint[0]` sufficient here?

2022-07-15 02:34 UTC, dpo commented on src/julia_interface.jl
> +  Jvar = @view(Array{Cint}(undef, nlp.meta.nvar + 1)[2:end])
This looks incredibly inefficient. I think we would be better off calling `jac_structure!()` and separating out ourselves the linear and the nonlinear part, and storing them inside the nlp. What do you think?

2022-07-15 02:34 UTC, dpo commented on src/julia_interface.jl
> +  Jvar = @view(Array{Cint}(undef, nlp.meta.nvar + 1)[2:end])
Or at the very least, Jval and Jvar should be preallocated and stored inside the nlp.

2022-07-15 02:34 UTC, dpo commented on src/julia_interface.jl
> +  Jvar = @view(Array{Cint}(undef, nlp.meta.nvar + 1)[2:end])
same comments here.

2022-07-15 02:34 UTC, dpo commented on src/julia_interface.jl
> +  jprod!(nlp, Vector{Float64}(x), Vector{Float64}(v), jvc)
since these constraints are linear, the Jacobian is constant and could be stored. Then we could compute a product efficiently.

2022-07-26 20:07 UTC, tmigot commented
This is ready for another review. Thanks for the comments, I think I fixed most of them and tried to improve.

2022-08-01 23:00 UTC, dpo reviewed
Looking good, thank you! The worry is that all those loops are slow, but currently, there's no other way.

2022-08-02 12:24 UTC, tmigot commented on src/julia_interface.jl
> +  cols[k:end] .= zero(Int32)
For `nnzj_nln`, I used `min(nvar * (ncon - nlin), nnzj)` (see https://github.com/JuliaSmoothOptimizers/CUTEst.jl/blob/e89575dc637af55ef78a09e804638cfaadbd79a0/src/CUTEst.jl#L349 from a previous PR).

The reason is that CUTEst only gives `nnzj` and I didn't want to evaluate the jacobian when first instantiating the model.

2022-08-02 12:30 UTC, tmigot commented on src/julia_interface.jl
> +end
From Nick Gould's advice, I understood that CUTEst doesn't redo computations for the linear constraints, so it was ok.

Still, I get your idea. Do you suggest we also compute the linear constraint within the function https://github.com/JuliaSmoothOptimizers/CUTEst.jl/blob/e89575dc637af55ef78a09e804638cfaadbd79a0/src/julia_interface.jl#L372 so that `cons_lin` just do the matrix-vector product + vector ?

2022-08-06 12:29 UTC, dpo commented on src/julia_interface.jl
> +end
Yes, but maybe just open an issue about it. That could be done later.

2022-08-06 12:29 UTC, dpo commented on src/julia_interface.jl
> +  cols[k:end] .= zero(Int32)
Ok thanks!

2022-08-06 12:29 UTC, dpo approved these changes

2022-08-08 12:35 UTC, merged