Added `increment!` and `decrement!` functions.
JuliaSmoothOptimizers/CUTEst.jl pull request #314
Opened 2023-10-01 05:31 UTC by Jay-sanjay

Fixes #292 
updated julia_interface.jl

2023-10-01 10:19 UTC, abelsiqueira commented
Hi @Jay-sanjay, thanks for the PR. Unfortunately, that is not the `increment!` that we wanted - our fault for not being clear on the issue. Check it here: https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/main/src/nlp.jl#L537

2023-10-01 11:31 UTC, Jay-sanjay commented
@abelsiqueira  sir do check is it the way the `increment!()` must be done , if yes I will update it for all other quantities too , that I did earlier

2023-10-01 18:32 UTC, abelsiqueira requested changes
Hi @Jay-sanjay, thanks. That is the correct usage, but you don't have to define the functions again since they are already present in the NLPModels.jl package.

2023-10-01 18:32 UTC, abelsiqueira commented on src/julia_interface.jl
> +
These shouldn't be necessary since they are already defined in NLPModels.jl. Just remove them.

2023-10-01 18:32 UTC, abelsiqueira commented on src/julia_interface.jl
> +  increment!(nlp, :neval_obj)
Yes, this is the correct usage.

2023-10-03 18:24 UTC, abelsiqueira approved these changes
Thanks @Jay-sanjay, this looks great.

2023-10-03 18:24 UTC, merged