Use cff instead of bib
JuliaSmoothOptimizers/CUTEst.jl pull request #322
Opened 2024-01-19 22:27 UTC by tmigot

2024-01-30 08:58 UTC, abelsiqueira requested changes
Same comments as https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/pull/131#event-11542388672

2024-01-30 08:58 UTC, abelsiqueira commented on CITATION.cff
> +    family-names: Siqueira
```suggestion
  - given-names: Abel
    family-names: Soares Siqueira
```

2024-01-30 08:58 UTC, abelsiqueira commented on CITATION.cff
> +commit: cf290bc63dd5b2a456ad84a3f7bf8dd089fc4074
```suggestion
```

2024-02-02 22:16 UTC, tmigot commented on CITATION.cff
> +      Montréal,             QC, Canada
```suggestion
    affiliation: >-
      GERAD and Department of Mathematics and            
      Industrial Engineering, Polytechnique
      Montréal, QC, Canada
```

2024-02-04 16:04 UTC, merged