Bump to NLPModels 0.21
JuliaSmoothOptimizers/CUTEst.jl pull request #327
Opened 2024-05-17 11:53 UTC by tmigot

2024-05-24 15:22 UTC, tmigot commented
Need https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/463

2024-05-24 22:16 UTC, tmigot commented
@amontoison @dpo @abelsiqueira  Not sure I have seen this error before https://github.com/JuliaSmoothOptimizers/CUTEst.jl/actions/runs/9226211936/job/25385471817?pr=327#step:7:162 any idea?

2024-05-29 11:34 UTC, dpo commented
Sorry, I missed this. Is the error occurring because of the NLPModels upgrade or because of an upgrade of CUTEst/SifDecode?

2024-05-29 11:49 UTC, dpo requested changes

2024-05-29 11:49 UTC, dpo commented on src/julia_interface.jl
> +  increment!(nlp, :neval_cons)
Well, isn't this the source of the error? You're incrementing `nevals_cons` even on unconstrained problems.

More generally, this pull request is about bumping the NLPModels version, but it does other things. I suggest removing the other changes so we can isolate the problem (if any).

2024-05-30 08:28 UTC, tmigot commented on src/julia_interface.jl
> +  increment!(nlp, :neval_cons)
This is part of the update to NLPModels 0.21. This was necessary to pass unit tests from NLPModelsTest that come along the new release.

Essentially, the idea is that we need to be consistent when calling cons! (and objcons!) on unconstrained problems.
I opened a new PR that updates link to better isolate the issue with the CI on macOS https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/328

2024-05-30 10:57 UTC, dpo commented on src/julia_interface.jl
> +  increment!(nlp, :neval_cons)
But what sense is there to incrementing `neval_cons` on an unconstrained problem?

2024-08-19 13:08 UTC, amontoison commented
@tmigot Is it possible to support NLPModels.jl v0.21 now?

2024-08-29 03:08 UTC, closed without merging