[CUTEst.jl] Support Windows
JuliaSmoothOptimizers/CUTEst.jl pull request #350
Opened 2024-08-18 00:32 UTC by amontoison

:crossed_fingers:

2024-08-18 00:45 UTC, amontoison commented
Wow, it works :flushed: :astonished: :scream: 
cc @dpo

2024-08-19 11:36 UTC, tmigot requested changes
That's really cool @amontoison, good job!
I am assuming this wouldn't work for anyone just testing directly on windows though, so we need a bit of documentation at least to warn them.

2024-08-19 11:36 UTC, tmigot commented on src/CUTEst.jl
>  function __init__()
```suggestion
function __init__()
```
Could you just add a comment around to say why we don't do anything for Windows here?

2024-08-19 12:13 UTC, amontoison commented on src/CUTEst.jl
>  function __init__()
It's because we don't have `bash` on Windows. I will add a comment in a different PR.

2024-08-19 12:16 UTC, amontoison commented
> That's really cool @amontoison, good job! I am assuming this wouldn't work for anyone just testing directly on windows though, so we need a bit of documentation at least to warn them.

Yes, we require the user to have a Fortran compiler `gfortran` for now but I know how to install it as an artifact for users so it will be very user-friendly in the future. I will reuse the artifacts of `Artifacts.toml` from PackageCompiler.jl.

2024-08-19 12:23 UTC, merged